apiVersion: v1
kind: Namespace
metadata:
  name: sveltekit-development
  labels:
    name: sveltekit-development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sveltekit-deployment
  namespace: sveltekit-development
  labels:
    app: sveltekit-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sveltekit-deployment
  template:
    metadata:
      labels:
        app: sveltekit-deployment
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: sveltekit-deployment
          image: 'lloyet/sveltekit:1.0.0'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: '512Mi'
              cpu: '250m'
            limits:
              cpu: '500m'
              memory: '1024Mi'
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 60
---
apiVersion: v1
kind: Service
metadata:
  name: sveltekit-service
  namespace: sveltekit-development
  labels:
    app: sveltekit-service
spec:
  type: NodePort
  selector:
    app: sveltekit-deployment
  ports:
    - port: 3000
      #protocole: TCP
      targetPort: 3000
      nodePort: 30000
